DELETE http://localhost:3001/api/persons/64a52d594cc04e1db09aa091

###

GET http://localhost:3001/api/persons

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Juliet",
    "number": "973-223121"
}

### 

GET http://localhost:3001/api/persons/64a52d594cc04e1db09aa091

###

PUT http://localhost:3001/api/persons/64a52d594cc04e1db09aa091
Content-Type: application/json

{
    "name": "juliet",
    "number": "97-32-223121"
}