DELETE http://localhost:3001/api/persons/193006

###

GET https://phonebook-backend-sawslin.fly.dev/api/persons

###

POST https://phonebook-backend-sawslin.fly.dev/api/persons
Content-Type: application/json

{
    "name": "Saw S. Lin",
    "number": "97-32-223121"
}