POST http://localhost:3001/api/patients
Content-Type: application/json

{
	"name": "Test",
	"dateOfBirth": "1990-09-11",
	"ssn": "323179-93G",
	"gender": "female",
	"occupation": "Journalist"
}

###
POST http://localhost:3001/api/patients
Content-Type: application/json

{
	"name": "Test",
	"dateOfBirth": "1994-05-13",
	"ssn": "323179-93G",
	"gender": "male",
	"occupation": "Journalist",
	"entries": []
}

###
POST http://localhost:3001/api/patients/36dc6a50-588a-11ee-bd3b-5b2fee3fd2de/entries
Content-Type: application/json

{
	"date": "2019-09-10",
	"specialist": "MD House",
	"type": "OccupationalHealthcare",
	"employerName": "FBI",
	"description": "Prescriptions renewed."
}

###
POST http://localhost:3001/api/patients/36dc6a50-588a-11ee-bd3b-5b2fee3fd2de/entries
Content-Type: application/json

{
	"date": "2018-10-05",
	"specialist": "MD House",
	"type": "HealthCheck",
	"description": "Yearly control visit. Due to high cholesterol levels recommended to eat more vegetables.",
	"healthCheckRating": 3
}

###
GET http://localhost:3001/api/patients/d2773598-f723-11e9-8f0b-362b9e155667 

### 
GET http://localhost:3001/api/patients/

###
GET http://localhost:3001/api/diagnoses/

###
PUT http://localhost:3001/api/patients/ab7e5c30-57bb-11ee-9131-478ca5642ab6
Content-Type: application/json

{
	"name": "Test 2",
	"dateOfBirth": "1994-05-13",
	"ssn": "323179-93G",
	"gender": "male",
	"occupation": "Journalist",
	"entries": [
		{
			"id": "b4f4eca1-2aa7-4b13-9a18-4a5535c3c8da",
			"date": "2019-10-20",
			"specialist": "MD House",
			"type": "HealthCheck",
			"description": "Yearly control visit. Cholesterol levels back to normal.",
			"healthCheckRating": 0
		},
		{
			"id": "fcd59fa6-c4b4-4fec-ac4d-df4fe1f85f62",
			"date": "2019-09-10",
			"specialist": "MD House",
			"type": "OccupationalHealthcare",
			"employerName": "FBI",
			"description": "Prescriptions renewed."
		},
		{
			"id": "37be178f-a432-4ba4-aac2-f86810e36a15",
			"date": "2018-10-05",
			"specialist": "MD House",
			"type": "HealthCheck",
			"description": "Yearly control visit. Due to high cholesterol levels recommended to eat more vegetables.",
			"healthCheckRating": 1
		}
	]
}