POST http://localhost:3002/exercises
Content-Type: application/json

{
  "daily_exercises": [1, 0, 2, 0, 3, 0, 2.5],
  "target": 2.5
}

###
# Bad request with missing params
POST http://localhost:3002/exercises
Content-Type: application/json

{
  "target": 2.5
}

###
# Bad request with malformatted params
POST http://localhost:3002/exercises
Content-Type: application/json

{
	"daily_exercises": [1, 0, 2, 0, 3, 0, 2.5],
  "target": "abc"
}

###
# Bad request with malformatted params
POST http://localhost:3002/exercises
Content-Type: application/json

{
	"daily_exercises": [1, "lol", 2, { "hello": 3.5 }, 3, 0, 2.5],
  "target": 2.5
}